# Generated by Django 4.1.4 on 2023-05-04 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('grade', models.FloatField(validators=[django.core.validators.MaxValueValidator(11, 'Should be 11'), django.core.validators.MinValueValidator(1, 'Should be 1')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.branch')),
            ],
        ),
    ]
